# Generated by Django 4.0 on 2021-12-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GameMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='User Name')),
                ('playerclass', models.CharField(choices=[('Knight', 'Knight'), ('Wizard', 'Wizard'), ('Thief', 'Thief'), ('Paladin', 'Paladin')], default='Knight', max_length=15, verbose_name='Player Class')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('level', models.IntegerField(default=0, verbose_name='Player Level')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GameMap.location')),
            ],
        ),
    ]
